### ISSUE TITLE
不要在 `config.json` 文件中设置 `"auth_token"` 字段!!!

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [langyamu/siyuan-calendar#1]
由于思源为 `widgets` 目录的提供的静态 Web 文件服务没有鉴权, 所以任何人都可以通过 `http(s)://host:port/widgets/siyuan-calendar/config.json` 获取到该配置文件, 如果用户更改了, 那么其 Token 就直接暴露了!

在实际应用中也无需使用 Token:
- 如果在思源文档内部通过挂件的形式使用, 那么由于没有发生跨域, 因此对所有请求都不鉴权
- 如果在浏览器中使用, 只要通过访问授权码登录过思源主界面, 那么所有请求都会附加包含登录状态的 `cookie`, 那么依然无需设置 Token

**Comment by langyamu** [comment]
好的，下个版本把这个去掉，我看思源 api 中有鉴权这一说以为需要加 token 呢，也没试不带token ，谢谢哈

**Comment by Zuoqiu-Yingyi** [comment]
还有一个问题, 挂件在更新时会使用新的 `config.json` 文件覆盖原文件, 建议将用户自定义文件设置在挂件目录外, 例如 `<工作空间>/data/widgets/config.json`

**Comment by langyamu** [comment]
放到公共空间里不知道会不会对之后有什么影响，先这样弄吧来回换json文件也够麻烦的，可惜没有一个获取挂件所在位置（笔记本/路径）的api 如果有的话 就不设置 config.json 了直接 读取笔记本配置就可以了

**Comment by Zuoqiu-Yingyi** [comment]
> 放到公共空间里不知道会不会对之后有什么影响，先这样弄吧来回换json文件也够麻烦的，可惜没有一个获取挂件所在位置（笔记本/路径）的api 如果有的话 就不设置 config.json 了直接 读取笔记本配置就可以了

有呀, 通过 `window.frameElement.parentElement.parentElement` 获得挂件所在的块
通过 `window.frameElement.parentElement.parentElement.dataset.nodeId` 获得挂件块的 ID
通过 `/api/query/sql` 查询挂件块的详细信息

**Comment by langyamu** [comment]
> > 放到公共空间里不知道会不会对之后有什么影响，先这样弄吧来回换json文件也够麻烦的，可惜没有一个获取挂件所在位置（笔记本/路径）的api 如果有的话 就不设置 config.json 了直接 读取笔记本配置就可以了
> 
> 有呀, 通过 `window.frameElement.parentElement.parentElement` 获得挂件所在的块 通过 `window.frameElement.parentElement.parentElement.dataset.nodeId` 获得挂件块的 ID 通过 `/api/query/sql` 查询挂件块的详细信息

好的，我试试，争取不用配置就能用

**Comment by Zuoqiu-Yingyi** [comment]
渲染模板可以使用一些未公开的 API
其中思源当前工作空间绝对路径在如下字段定义
`window.top.siyuan.config.system.workspaceDir === 'D:\\Notebook\\Siyuan\\workspace\\'`

## 获取模板列表

* `/api/search/searchTemplate`
* 参数

  * ```json
    {
        "k": ""
    }
    ```

    * `k`: 搜索时的关键字
* 响应

  * ```json
    {
        "code": 0,
        "msg": "",
        "data": {
            "blocks": [
                {"box":"","path":"D:\\Notebook\\Siyuan\\workspace\\data\\templates\\2-工具\\当前文档ID.md","hPath":"","id":"","rootID":"","parentID":"","name":"","alias":"","memo":"","content":"2-工具/当前文档ID","fcontent":"","markdown":"","folded":false,"type":"","subType":"","refText":"","refs":null,"defID":"","defPath":"","ial":null,"children":null,"depth":0,"count":0},
            ],
            "k":""
        }
    }

    ```

## 渲染模板

* `/api/template/render`
* 参数

  * ```json
    {
        "id": "20220429183903-7glamaq",
        "path": "D:\\Notebook\\Siyuan\\workspace\\data\\templates\\2-工具\\当前文档ID.md"
    }
    ```
  * `id`: 当前文档 ID
  * `path`: 模板文件绝对路径
* 响应

  * ```json
    {
        "code": 0,
        "msg": "",
        "data": {
            "content": "\u003cdiv data-node-id=\"20220429222347-gc1mw9t\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\" updated=\"20220429222347\"\u003e\u003cdiv contenteditable=\"true\" spellcheck=\"false\"\u003e20220429183903-7glamaq\u003c/div\u003e\u003cdiv class=\"protyle-attr\" contenteditable=\"false\"\u003e​\u003c/div\u003e\u003c/div\u003e\u003cdiv data-node-id=\"20220429222347-ytczh8f\" data-node-index=\"2\" data-type=\"NodeParagraph\" class=\"p\" updated=\"20220429222347\"\u003e\u003cdiv contenteditable=\"true\" spellcheck=\"false\"\u003e新文\ufffd\u003c/div\u003e\u003cdiv class=\"protyle-attr\" contenteditable=\"false\"\u003e​\u003c/div\u003e\u003c/div\u003e",
            "path": "D:\\Notebook\\Siyuan\\workspace\\data\\templates\\2-工具\\当前文档ID.md"
        }
    }
    ```

**Comment by langyamu** [comment]
好的，我试试

**Comment by Zuoqiu-Yingyi** [comment]
@langyamu 对了, 刚刚 D 大给你发送了开发者群的邀请, 如果想加入的话可以同意一下

可以使用 `window.top.localStorage.getItem('local-dailynoteid')` 获得 Daliy Note 的笔记本 ID, 然后使用如下  API 自动创建文档 + 自动笔记本设置的 Daliy Note 模板

## 创建 Daliy Note

* `/api/filetree/createDailyNote`
* 请求

  * ```json
    {
        "notebook": "20210808180117-czj9bvb"
    }
    ```
  * `notebook`: 笔记本
* 响应

  * ```json
    {
        "code": 0,
        "msg": "",
        "data": null
    }
    ```

**Comment by langyamu** [comment]
@Zuoqiu-Yingyi 
加进去了，有了这个接口就省的去获取父窗口的信息再查库了，但总觉的咱们这样通过父窗口获取信息不太友好，有些信息需要 build 后放到指定目录下才能获取到data，而开发环境下一般都是独立在一个浏览器页签里的，我意思是咱们要不统一一下，要么都从 api 获取 要么 都从 父窗口里获取

**Comment by langyamu** [comment]
@Zuoqiu-Yingyi

这个 'local-dailynoteid' 我试了一下，是点完**思源笔记**顶部的 **日记按钮** 后才会发生改变，在有多个 笔记本时 可能会获取错成别的笔记本的id

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi 加进去了，有了这个接口就省的去获取父窗口的信息再查库了，但总觉的咱们这样通过父窗口获取信息不太友好，有些信息需要 build 后放到指定目录下才能获取到data，而开发环境下一般都是独立在一个浏览器页签里的，我意思是咱们要不统一一下，要么都从 api 获取 要么 都从 父窗口里获取

这里指哪个接口与哪个 API 呀

**Comment by langyamu** [comment]
额是我这边学艺不精，我用的ts，涉及到 父窗口的 window 数据是需要自己手动加类型的，之前没get到这个点 走了点弯路哈哈

**Comment by Zuoqiu-Yingyi** [comment]
> 额是我这边学艺不精，我用的ts，涉及到 父窗口的 window 数据是需要自己手动加类型的，之前没get到这个点 走了点弯路哈哈

不过挂件貌似只能通过父窗口获得自身的块 ID, 浏览器打开一般都需要通过 URL 参数传入其自身的块 ID
