### ISSUE TITLE
【求助】安装 siyuan-calendar 后日记和事项为空白

### ISSUE THREAD

**Issue by SkysCrystal** [langyamu/siyuan-calendar#11]
安装挂件不能显示日记和事项，全部页面在文档部分显示。
![Daily work](https://pan.swin.ltd/d/basic/Figurebed/202302070935121.png)

笔记本日记设置
![daily notes setting](https://pan.swin.ltd/d/basic/Figurebed/202302070937841.png)
这样应该是符合 `/prefix/YYYY/MM/YYYY-MM-DD` 形式，最新的日记是安装插件后创建的（插件安装了挺久，之前没挂到页面上）

siyuan-calendar 当前版本 v0.0.6

**Comment by langyamu** [comment]
![image](https://user-images.githubusercontent.com/40269393/217133185-a66a20a7-9f2f-4a81-8ee9-01c4492c0533.png)
你去设置里切换下显示模式，再选则下笔记本试试

**Comment by SkysCrystal** [comment]
尝试切换了，但还是不行

**Comment by langyamu** [comment]
> 

我看看你写的都是啥待办事项

**Comment by SkysCrystal** [comment]
> > 
> 
> 我看看你写的都是啥待办事项

我发现在新创建的页面上建立的 [ ] 块（代办）可以显示：
![](https://pan.swin.ltd/d/basic/Figurebed/202302082154436.png)

但是日记还是无法显示，会显示在文档部分：
![日记在文档显示](https://pan.swin.ltd/d/basic/Figurebed/202302082153239.png)
