### ISSUE TITLE
建议路径配置能在挂件中绑定，而不是去修改笔记配置

### ISSUE THREAD

**Issue by o-ut-man** [langyamu/siyuan-calendar#3]
修改笔记配置会影响当前的文件结构，而且后续如果不使用挂件的话，又需要重新修改。
所以建议直接在挂件中绑定路径。

**Comment by langyamu** [comment]
> 修改笔记配置会影响当前的文件结构，而且后续如果不使用挂件的话，又需要重新修改。 所以建议直接在挂件中绑定路径。

![image](https://user-images.githubusercontent.com/40269393/169520378-3100be5e-7431-4830-bf2b-9f4b2906793e.png)
如果按照说明图片里配置 目录结构是这样的，当初这么设计也是为了能将配置最小化，底层 检索 日记文档的 sql 写起来 也不用猜用户是哪种目录结构（直接规定都是这个结构的，否则 各种奇葩的结构，没法做判断） 

我是这样做日期与每日笔记的对应关系的，通过以下 sql 将日期对应的文档 数据查出，然后拼接成 思源的超链接 `siyuan://blocks/${newData[0].root_id}` 之后再进行跳转

```sql
  SELECT
            *
        FROM
            blocks
        WHERE
            hpath = '/Work Bench/2022/05/20'
            and type = 'd'
            and box = '${$notebook_id.value}'
        order by
                created
  
```
总不能将sql暴露出去让用户去写吧。。
